#pragma once

#include "engine/engine.h"
#include "engine/camera.h"
#include "engine/mesh.h"
#include "engine/node.h"
#include "engine/perspective_camera.h"
#include "engine/scene.h"
#include "engine/timer.h"

#include "engine/components/component.h"
#include "engine/components/camera_component.h"
#include "engine/components/constraint_component.h"
#include "engine/components/dynamic_body_component.h"
#include "engine/components/kinematic_body_component.h"
#include "engine/components/light_component.h"
#include "engine/components/mesh_component.h"
#include "engine/components/physics_world_component.h"
#include "engine/components/sprite_component.h"
#include "engine/components/static_body_component.h"
#include "engine/components/text_component.h"
#include "engine/components/trigger_component.h"

#include "engine/math/matrix.h"
#include "engine/math/quaternion.h"
#include "engine/math/transform.h"
#include "engine/math/vector.h"

#include "engine/mixins/engine_access_mixin.h"
#include "engine/sequence/sequence.h"
#include "engine/sequence/sequence_instance.h"
#include "engine/sequence/actions/action.h"
#include "engine/sequence/actions/call_function.h"
#include "engine/sequence/actions/linear_action.h"
#include "engine/sequence/actions/wait_action.h"

#include "engine/subsystems/subsystem_interface.h"

#include "engine/subsystems/file_manager/file_manager_subsystem.h"

#include "engine/subsystems/graphics/font.h"
#include "engine/subsystems/graphics/graphics_subsystem.h"
#include "engine/subsystems/graphics/index_buffer.h"
#include "engine/subsystems/graphics/light_source.h"
#include "engine/subsystems/graphics/material.h"
#include "engine/subsystems/graphics/mesh_renderer.h"
#include "engine/subsystems/graphics/shader_program.h"
#include "engine/subsystems/graphics/sprite.h"
#include "engine/subsystems/graphics/texture.h"
#include "engine/subsystems/graphics/vertex_buffer.h"

#include "engine/subsystems/graphics/opengl/glsl_shader_program.h"
#include "engine/subsystems/graphics/opengl/opengl_graphics_subsystem.h"
#include "engine/subsystems/graphics/opengl/opengl_mesh_renderer.h"
#include "engine/subsystems/graphics/opengl/opengl_index_buffer.h"
#include "engine/subsystems/graphics/opengl/opengl_texture.h"
#include "engine/subsystems/graphics/opengl/opengl_vertex_array_buffer.h"
#include "engine/subsystems/graphics/opengl/opengl_vertex_buffer.h"

#include "engine/subsystems/input/gamepad.h"
#include "engine/subsystems/input/input_axis.h"
#include "engine/subsystems/input/input_button.h"
#include "engine/subsystems/input/input_subsystem.h"
#include "engine/subsystems/input/keyboard.h"
#include "engine/subsystems/input/mouse.h"
#include "engine/subsystems/input/glfw/glfw_input_subsystem.h"

#include "engine/subsystems/physics/collision_shape.h"
#include "engine/subsystems/physics/constraint.h"
#include "engine/subsystems/physics/contact.h"
#include "engine/subsystems/physics/hit_info.h"
#include "engine/subsystems/physics/physics_body.h"
#include "engine/subsystems/physics/physics_subsystem.h"
#include "engine/subsystems/physics/physics_world.h"

#include "engine/subsystems/physics/bullet/bullet_box_collision_shape.h"
#include "engine/subsystems/physics/bullet/bullet_collision_shape.h"
#include "engine/subsystems/physics/bullet/bullet_constraint.h"
#include "engine/subsystems/physics/bullet/bullet_mesh_collision_shape.h"
#include "engine/subsystems/physics/bullet/bullet_physics_body.h"
#include "engine/subsystems/physics/bullet/bullet_physics_subsystem.h"
#include "engine/subsystems/physics/bullet/bullet_physics_world.h"
#include "engine/subsystems/physics/bullet/bullet_sphere_collision_shape.h"

#include "engine/subsystems/scene_manager/scene_manager_subsystem.h"

#include "engine/subsystems/window_manager/window_manager_subsystem.h"
#include "engine/subsystems/window_manager/glfw/glfw_window_manager_subsystem.h"